### ISSUE TITLE
declarations/pattern_parser.py:109 Assertion fail

### ISSUE THREAD

**Issue by chenghuige** [gccxml/pygccxml#60] opened 2016-07-09 13:25 UTC
When using pyplusplus, I face this problem when finally write result, and if comment out , I can get wrapper code generated.

    def split(self, decl_string):
        """implementation details"""
        #assert self.has_pattern(decl_string)
        return self.name(decl_string), self.args(decl_string)

**Comment by mamoll** [comment] 2016-07-09 14:26
It'd be helpful if you could attach a minimal code sample that triggers this assertion.

**Comment by chenghuige** [comment] 2016-07-10 04:55
@mamoll 
Well, I find the problem is due to parsing 
#include <boost/locale.hpp>

which will result below， printing the decl_string

decl_string: std::vector<char, std::allocator<char> > (const std::string & self.__begin: < self.__end: >
decl_string: std::vector<char, std::allocator<char> > (const std::string & self.__begin: < self.__end: >
decl_string: std::vector<char, std::allocator<char> > (const std::string & self.__begin: < self.__end: >

**Comment by iMichka** [comment] 2016-07-10 08:56
Hi. Thanks for reporting this.

- Is this with pygccxml 1.7.6 or the current develop version ?
- Are you using gccxml or castxml as xml generator ?
- On what OS is this happening.

**Comment by chenghuige** [comment] 2016-07-10 10:33
@iMichka 
The current develop version.
Using castxml, on centos.

**Comment by iMichka** [comment] 2016-07-11 21:59
I could reproduce the problem. I'll have a look in the next days.

**Comment by iMichka** [comment] 2016-07-14 21:25
Note to myself. The code that fails is:

```
#include <boost/locale.hpp>
using namespace boost::locale;

int main()
{
    generator gen;
    std::locale::global(gen(""));
}
```

```
decls = parser.parse([self.header], self.config)
global_ns = declarations.get_global_namespace(decls)
criteria = declarations.declaration_matcher(name="gen")
decls = declarations.matcher.find(criteria, global_ns)
print(decls[0])
```

The name of the declaration is:
```boost::function<std::vector<char, std::allocator<char> > (const std::basic_string<char> &, const std::basic_string<char> &)> [class]```

The failure is happening while the ```partial_name``` is generated.

I was able to find the declaration in the tree, I need now to understand what is failing now. This may take a little bit of time, as this is in a very tricky part of the code. Also it does not help that this is happening in the boost code ... which is fairly complex.

If you need a quickfix, just remove the asserts, that should not influence the building with pyplusplus.

**Comment by iMichka** [comment] 2016-07-26 22:02
Ok I found the problem. I wrote a fix but still need to extend the tests a little bit. I hope I will be able to push my patch tomorrow.

**Comment by iMichka** [comment] 2016-07-27 21:38
I pushed the fix. I also added a bunch of tests for that case.
Could you test again with the latest develop version ? If it's working you can then close this bug.

@mamoll the change was quite big. I hope I did not break anything. The 1.8.0 release will be around September (after my holidays), so there is still room for testing. If something comes up due to these changes don't hesitate, I'll have a look.

**Comment by iMichka** [comment] 2016-08-29 22:07
@chenghuige I am closing this bug, as I consider as the reported problem being solved. Please open a new bug if this is not the case. Thanks.

**Closed by iMichka** 2016-08-29 22:07 UTC
Labels: bug
